language: python

python:
  - "2.7"

matrix:
  include:
    - python: "2.7"
      env: TOXARG="-e pylint"

sudo: false

install:
    - pip install tox-travis

script:
    - tox $TOXARG

deploy:
  provider: pypi
  user: edx
  password:
    secure: sQ2Ct0BA5JAhj6cNt+MFcbeCa/SJW2PlWiuD5/KLgszx7D58yrPnP/E87YF5JAtyUhzpaEt92G1hKWXEi2HW6jE6IfMye75kqMK1Wy7JCYXZNxxIYC6MfXH0kHfNasT1rJ7MpHFDV5EdcSInSJMY6oWbMHQ5CU+2K3d5zUz1EpY=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
