language: python

python:
  - 2.7
  - 3.5
matrix:
 include:
  - python: "2.7"
    env: TOXARG="-e pylint"

sudo: false

install:
    - pip install tox-travis

script:
    - tox $TOXARG

deploy:
  provider: pypi
  user: edx
  password:
    secure: wWYHDIO61/n8faB2JF4l6MiiJcu2jaReQU3eZ8zWCVKw2+AjxuC1skrst3+x4Nao1U72I33IajIXT6oa8ALAFOke0ViC4TSAdGkLrQChAS1hCU0yW02LDGeV5Y7V262uLVH+4rsNk5388f5Nta8LHER7SBI6f5UUbxScG2vkx18=
  distributions: sdist bdist_wheel
  on:
    tags: true
